# Change to `true` to turn on dependency checks for this package
enforce_dependencies: true 

# A list of this package's dependencies
# Note that packages in this list require their own `package.yml` file
dependencies:
# Base controllers/models are defined in the root
- .
